In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Hotel_Reviews.csv')
df.head()

Hotel_Address  \
0   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
1   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
2   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
3   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   
4   s Gravesandestraat 55 Oost 1092 AA Amsterdam ...   

   Additional_Number_of_Scoring Review_Date  Average_Score   Hotel_Name  \
0                           194    8/3/2017            7.7  Hotel Arena   
1                           194    8/3/2017            7.7  Hotel Arena   
2                           194   7/31/2017            7.7  Hotel Arena   
3                           194   7/31/2017            7.7  Hotel Arena   
4                           194   7/24/2017            7.7  Hotel Arena   

  Reviewer_Nationality                                    Negative_Review  \
0              Russia    I am so angry that i made this post available...   
1             Ireland                                         No Negative   
2           Australia    Rooms are nice but for elderly a bit difficul...   
3      United Kingdom    My room was dirty and I was afraid to walk ba...   
4         New Zealand    You When I booked with your company on line y...   

   Review_Total_Negative_Word_Counts  Total_Number_of_Reviews  \
0                                397                     1403   
1                                  0                     1403   
2                                 42                     1403   
3                                210                     1403   
4                                140                     1403   

                                     Positive_Review  \
0   Only the park outside of the hotel was beauti...   
1   No real complaints the hotel was great great ...   
2   Location was good and staff were ok It is cut...   
3   Great location in nice surroundings the bar a...   
4    Amazing location and building Romantic setting    

   Review_Total_Positive_Word_Counts  \
0                                 11   
1                                105   
2                                 21   
3                                 26   
4                                  8   

   Total_Number_of_Reviews_Reviewer_Has_Given  Reviewer_Score  \
0                                           7             2.9   
1                                           7             7.5   
2                                           9             7.1   
3                                           1             3.8   
4                                           3             6.7   

                                                Tags days_since_review  \
0  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
1  [' Leisure trip ', ' Couple ', ' Duplex Double...            0 days   
2  [' Leisure trip ', ' Family with young childre...            3 days   
3  [' Leisure trip ', ' Solo traveler ', ' Duplex...            3 days   
4  [' Leisure trip ', ' Couple ', ' Suite ', ' St...           10 days   

         lat       lng  
0  52.360576  4.915968  
1  52.360576  4.915968  
2  52.360576  4.915968  
3  52.360576  4.915968  
4  52.360576  4.915968

In [3]:
df_new = df[['Negative_Review','Positive_Review']]

In [4]:
df_new

Negative_Review  \
0        I am so angry that i made this post available...   
1                                             No Negative   
2        Rooms are nice but for elderly a bit difficul...   
3        My room was dirty and I was afraid to walk ba...   
4        You When I booked with your company on line y...   
...                                                   ...   
515733   no trolly or staff to help you take the lugga...   
515734           The hotel looks like 3 but surely not 4    
515735   The ac was useless It was a hot week in vienn...   
515736                                        No Negative   
515737       I was in 3rd floor It didn t work Free Wife    

                                          Positive_Review  
0        Only the park outside of the hotel was beauti...  
1        No real complaints the hotel was great great ...  
2        Location was good and staff were ok It is cut...  
3        Great location in nice surroundings the bar a...  
4         Amazing location and building Romantic setting   
...                                                   ...  
515733                                           location  
515734      Breakfast was ok and we got earlier check in   
515735                                        No Positive  
515736   The rooms are enormous and really comfortable...  
515737                               staff was very kind   

[515738 rows x 2 columns]

In [5]:
temp = pd.concat([df_new['Negative_Review'][:10000], df_new['Positive_Review'][:10000]],axis=0).reset_index()

In [6]:
temp = temp.drop(['index'],axis=1)

In [7]:
temp['sentiment'] = 0

In [8]:
temp.rename(columns={0:'review'}, inplace=True)

In [9]:
temp[9999:10010]

review  sentiment
9999                                Windows Were broken           0
10000   Only the park outside of the hotel was beauti...          0
10001   No real complaints the hotel was great great ...          0
10002   Location was good and staff were ok It is cut...          0
10003   Great location in nice surroundings the bar a...          0
10004    Amazing location and building Romantic setting           0
10005   Good restaurant with modern design great chil...          0
10006   The room is spacious and bright The hotel is ...          0
10007   Good location Set in a lovely park friendly s...          0
10008                                        No Positive          0
10009   The room was big enough and the bed is good T...          0

In [10]:
for i in range(0,20000):
    if i >= 10000:
        temp['sentiment'][i] = 1

<ipython-input-10-68f3fd4aba5a>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  temp['sentiment'][i] = 1


In [31]:
temp

review  sentiment
0       I am so angry that i made this post available...          0
1                                            No Negative          0
2       Rooms are nice but for elderly a bit difficul...          0
3       My room was dirty and I was afraid to walk ba...          0
4       You When I booked with your company on line y...          0
...                                                  ...        ...
19995                                      perfect staff          1
19996                      The staff are really friendly          1
19997                                           Friendly          1
19998   Beds were extra comfy Staff very friendly and...          1
19999                             Breakfast Was horible           1

[20000 rows x 2 columns]

In [13]:
temp.to_csv('processed_data.csv')

In [27]:
data = temp.copy()

In [28]:
import re
import nltk
from nltk.stem.porter import PorterStemmer
from nltk.corpus import stopwords

In [33]:
ps = PorterStemmer()

for i in range(len(data)):
    data['review'][i] = re.sub('[^a-zA-Z]', " ",data['review'][i])
    
    sent = data['review'][i].split()
    
    sent = [ps.stem(word) for word in sent if word not in stopwords.words('english')]
    
    sent = ' '.join(sent)
    
    data['review'][i] = sent
    

<ipython-input-33-91ef6d73547a>:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][i] = re.sub('[^a-zA-Z]', " ",data['review'][i])
<ipython-input-33-91ef6d73547a>:12: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['review'][i] = sent


In [16]:
temp['review'][0]

' I am so angry that i made this post available via all possible sites i use when planing my trips so no one will make the mistake of booking this place I made my booking via booking com We stayed for 6 nights in this hotel from 11 to 17 July Upon arrival we were placed in a small room on the 2nd floor of the hotel It turned out that this was not the room we booked I had specially reserved the 2 level duplex room so that we would have a big windows and high ceilings The room itself was ok if you don t mind the broken window that can not be closed hello rain and a mini fridge that contained some sort of a bio weapon at least i guessed so by the smell of it I intimately asked to change the room and after explaining 2 times that i booked a duplex btw it costs the same as a simple double but got way more volume due to the high ceiling was offered a room but only the next day SO i had to check out the next day before 11 o clock in order to get the room i waned to Not the best way to begin y

In [35]:
data['review'][0]

'i angri made post avail via possibl site use plane trip one make mistak book place i made book via book com we stay night hotel juli upon arriv place small room nd floor hotel it turn room book i special reserv level duplex room would big window high ceil the room ok mind broken window close hello rain mini fridg contain sort bio weapon least guess smell i intim ask chang room explain time book duplex btw cost simpl doubl got way volum due high ceil offer room next day so check next day clock order get room wane not best way begin holiday so wait till order check new room wonder waist time the room got want peac intern garden view big window we tire wait room place belong rush citi in even turn constant nois room guess made vibrat vent tube someth constant annoy hell and stop even make hard fall asleep wife i audio record attach want send via e mail the next day technician came abl determin caus disturb sound offer chang room hotel fulli book room left one smaller seem newer'

In [34]:
data

review  sentiment
0      i angri made post avail via possibl site use p...          0
1                                                 no neg          0
2      room nice elderli bit difficult room two stori...          0
3      my room dirti i afraid walk barefoot floor loo...          0
4      you when i book compani line show pictur room ...          0
...                                                  ...        ...
19995                                      perfect staff          1
19996                          the staff realli friendli          1
19997                                           friendli          1
19998                bed extra comfi staff friendli help          1
19999                                breakfast wa horibl          1

[20000 rows x 2 columns]

In [36]:
data.to_csv('nltk_processed_data.csv')

In [38]:
X = data['review']
y = data['sentiment']

# Word Embedding

In [37]:
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

#### One hot

In [40]:
voc_size = 50000

onehot_repr = [ one_hot(word,voc_size) for word in X]
onehot_repr

[[26277,
  25514,
  30127,
  4927,
  49233,
  21150,
  31364,
  13871,
  30361,
  30629,
  31711,
  8534,
  24140,
  42378,
  44850,
  36445,
  26277,
  30127,
  44850,
  21150,
  44850,
  11188,
  13367,
  8037,
  28378,
  11596,
  16706,
  5954,
  9657,
  36445,
  37720,
  20792,
  26754,
  36778,
  11596,
  24018,
  29981,
  20792,
  44850,
  26277,
  24958,
  39211,
  29502,
  16617,
  20792,
  34949,
  42375,
  13208,
  4912,
  5868,
  11317,
  20792,
  17327,
  24806,
  2490,
  13208,
  11777,
  41547,
  2407,
  13518,
  46119,
  33995,
  1355,
  2496,
  26083,
  21962,
  11690,
  32173,
  26277,
  4427,
  18537,
  32836,
  20792,
  1784,
  29508,
  44850,
  16617,
  40084,
  28554,
  23385,
  20764,
  37961,
  21943,
  3879,
  43531,
  4912,
  5868,
  9866,
  20792,
  37706,
  24086,
  35737,
  15300,
  37706,
  24086,
  36492,
  32514,
  48038,
  20792,
  49087,
  23506,
  48572,
  21943,
  9841,
  4524,
  35737,
  23849,
  18463,
  32514,
  15300,
  33179,
  20792,
  10296,
  

In [43]:
sent_length = 1000
embedded_docs = pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
embedded_docs

array([[    0,     0,     0, ..., 19503, 12826,  3903],
       [    0,     0,     0, ...,     0,  7691, 40289],
       [    0,     0,     0, ..., 35935, 22791, 46119],
       ...,
       [    0,     0,     0, ...,     0,     0, 37611],
       [    0,     0,     0, ..., 30549, 37611, 15459],
       [    0,     0,     0, ..., 12384, 19544, 34014]])

# Creating model

In [45]:
from tensorflow.keras.layers import LSTM, Dense, Dropout, Embedding
from tensorflow.keras.models import Sequential

In [47]:
embedding_vector_featres = 64

model = Sequential()
model.add(Embedding(voc_size,embedding_vector_featres,input_length=sent_length))
model.add(Dropout(0.4))
model.add(LSTM(128))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 1000, 64)          3200000   
_________________________________________________________________
dropout_2 (Dropout)          (None, 1000, 64)          0         
_________________________________________________________________
lstm_1 (LSTM)                (None, 128)               98816     
_________________________________________________________________
dropout_3 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 129       
Total params: 3,298,945
Trainable params: 3,298,945
Non-trainable params: 0
_________________________________________________________________


In [49]:
import numpy as np

X_final = np.array(embedded_docs)
y_final = np.array(y)

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_final,y_final,test_size=0.2,random_state=42)

# Model Tranining

In [52]:
model.fit(X_train,y_train,validation_data=(X_test,y_test), epochs=2, batch_size=32)

Epoch 1/2
500/500 [==============================] - 483s 966ms/step - loss: 0.2053 - accuracy: 0.9245 - val_loss: 0.1845 - val_accuracy: 0.9310
Epoch 2/2
500/500 [==============================] - 385s 770ms/step - loss: 0.1605 - accuracy: 0.9424 - val_loss: 0.1722 - val_accuracy: 0.9388


In [54]:
from sklearn.metrics import confusion_matrix

y_pred = model.predict_classes(X_test)

confusion_matrix(y_test,y_pred)

array([[1888,  131],
       [ 114, 1867]], dtype=int64)

In [72]:
voc_size = 50000
word = "the food is good bad "
onehot_repr_test = [ one_hot(word,voc_size) ]
onehot_repr_test

[[11317, 5157, 16580, 24399, 10230]]

In [73]:
sent_length = 1000
embedded_docs_test = pad_sequences(onehot_repr_test,padding='pre',maxlen=sent_length)
embedded_docs_test

array([[    0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
      

In [74]:
test_sent = np.array(embedded_docs_test)

In [75]:
y_pred_test = model.predict(test_sent)

In [76]:
y_pred_test

array([[0.37059906]], dtype=float32)

In [81]:
model.save('model')

INFO:tensorflow:Assets written to: model\assets
